### ISSUE TITLE
Collapsed menu buttons miss tooltips

### ISSUE THREAD

**Issue by maettig** [devmount/SongDrive#43]
On narrow screens (e.g. mobile devices) the menus on the left collapse, which is great. But it creates a few issues:
1. Some of the buttons use the same icon, making them virtually indistinguishable.
2. It appears like the buttons don't have `title="…"` attributes. This would help a lot at least on devices with a mouse. Unfortunately it won't help on touch devices.

Screenshot:
![Screenshot from 2021-03-21 15-55-36](https://user-images.githubusercontent.com/1177987/111909538-f9a71380-8a5d-11eb-8f5a-7bf845dbd78e.png)

Disclaimer: I understand what I report here is most certainly intentionally designed like this, and hard to change.

**Comment by devmount** [comment]
Thank you for this report. This is actually a bug, since tooltips should appear on mouse over to the right of each button.

1. SongDrive uses Ionicons as icon lib, which doesn't provide icons for different file or download types. I'll consider switching to a more feature rich icon lib
2. As soon as tooltips are activated again, this shouldn't be aproblem anymore for devices with mouse. On touch devices you will need to hold on a button to trigger the tooltip without triggering the button action.
