### ISSUE TITLE
Scaled text is sometimes hard to or unreadable

### ISSUE THREAD

**Issue by maettig** [devmount/SongDrive#45]
The text scaling algorithm is just amazing, especially in presentation mode. Don't get me wrong. I find it fascinating to see how it figures out how the text might fit on the screen, and pretty much always succeeds. Still there are edge cases. Here are two extreme example screenshots:

![Screenshot from 2021-03-21 16-16-25](https://user-images.githubusercontent.com/1177987/111910243-daf64c00-8a60-11eb-9586-c98ced996492.png)
![Screenshot from 2021-03-21 16-22-28](https://user-images.githubusercontent.com/1177987/111910445-adf66900-8a61-11eb-9095-539ffba46bb0.png)

This looks a little confusing, like one of the verses is more important than the other, or I need to sing this one louder. ;-) Sometimes the text is so small it becomes unreadable. I wonder what happens if you give the algorithm a minimum and a maximum font size? Or try to use the same scaling for all verses?

**Comment by devmount** [comment]
The presentation mode was designed to fit the whole song into the viewport so that the musician won't be forced to scroll when performing a song. In a first step, it scales every single song part that its longest line of text fits into the available width. In a second step all song parts are scaled equally to fit into in the viewport height.

> I wonder what happens if you give the algorithm a minimum and a maximum font size

This is a great idea, I will experiment with this a little to see, if at least the "loudest parts" can be reduced 👍🏻 

> Or try to use the same scaling for all verses?

Also a very good idea - this will bring some consistency at least for all verses.

**Comment by devmount** [comment]
I made some improvements for this and the overall scaling should be more smooth now. Also a maximum font size is now taken into account. Here is the look of the example song given above:

![songdrive_scaling1](https://user-images.githubusercontent.com/5441654/168556119-ef2dff71-8d59-4972-85af-64bb3012b656.png)
![songdrive_scaling2](https://user-images.githubusercontent.com/5441654/168556138-754e6d22-b234-4d9d-b39f-a00746dc4e19.png)

Will be part of the next release.

It's still not optimal and still recommended to use SongDrive on larger Screens (at least HD achieves the good results). Optimization for mobile device will be implemented in the future.
